#!/usr/bin/env sh
set -eu

# POSIX compliant version of readlink
# Credit: https://github.com/ko1nksm/readlinkf

if [ ${#} -eq 0 ]; then
    printf "%s\n" "readlinkf: no file path provided"
    exit 0
fi

[ "${1:-}" ] || return 1

max_symlinks=40
# to avoid changing to an unexpected directory
CDPATH=''
target=${1}

# trim trailing slashes
[ -e "${target%/}" ] || target=${1%"${1##*[!/]}"}
[ -d "${target:-/}" ] && target="$target/"

cd -P . 2>/dev/null || return 1
while [ "$max_symlinks" -ge 0 ] && max_symlinks=$((max_symlinks - 1)); do
    if [ ! "$target" = "${target%/*}" ]; then
        case $target in
            /*) cd -P "${target%/*}/" 2>/dev/null || break ;;
            *) cd -P "./${target%/*}" 2>/dev/null || break ;;
        esac
        target=${target##*/}
    fi
    if [ ! -L "$target" ]; then
        target="${PWD%/}${target:+/}${target}"
        printf '%s\n' "${target:-/}"
        exit 0
    fi
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/ls.html
    link=$(ls -dl -- "$target" 2>/dev/null) || break
    target=${link#*" $target -> "}
done

exit 1
